language: rust
os: linux
dist: xenial

script:
  - rustup toolchain install nightly
  - cargo +nightly update -Z minimal-versions
  - cargo build --manifest-path vk-parse/Cargo.toml --features ""
  - cargo build --manifest-path vk-parse/Cargo.toml --features "serialize"
  - cargo build --manifest-path vk-parse/Cargo.toml --features "vkxml-convert"
  - cargo build --manifest-path vk-parse/Cargo.toml --features "serialize,vkxml-convert"
  - cargo build --all
  - cargo test --all

rust:
  - 1.40.0
  - stable
  - beta
  - nightly

jobs:
  include:
    - dist: bionic
      rust: 1.40.0
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

notifications:
  email:
    recipients:
      - kroslakma@gmail.com
    on_success: change
    on_failure: always
