name: Continuous integration
on:
  schedule:
    - cron: '0 16 * * *'
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.40.0 # MSRV (Minimum supported Rust version)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
          toolchain: ${{ matrix.rust }}

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: false
          toolchain: nightly

      # Using -Z minimal-versions is less work than manually maintained Cargo.lock
      # file for testing minimal versions. However, dev-dependencies can cause issues
      # with this approach so we're keeping them in separate crate.
      # See https://github.com/rust-lang/api-guidelines/pull/227#discussion_r527081699
      - name: Update to minimal versions
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: update
          args: -Z minimal-versions

      - name: 'Build'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path vk-parse/Cargo.toml --features ""

      - name: 'Build (features: serialize)'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path vk-parse/Cargo.toml --features "serialize"

      - name: 'Build (features: vkxml-convert)'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path vk-parse/Cargo.toml --features "vkxml-convert"

      - name: 'Build (features: serialize,vkxml-convert)'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path vk-parse/Cargo.toml --features "serialize,vkxml-convert"

      - name: 'Build all'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: 'Test all'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
